version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bip39
    versions:
    - 3.0.3
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: pbkdf2
    versions:
    - 3.1.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
